---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: Creates a user
      parameters: []
      responses:
        '200':
          description: user created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
                user_name:
                  type: string
  "/users/sign_in":
    post:
      summary: sign_in
      parameters: []
      responses:
        '200':
          description: sign_in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/api/v1
